FROM nvidia/cuda:{{CUDA_VERSION}}-devel-ubuntu20.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    cmake \
    gdb \
    git \
    libopencv-dev \
    ninja-build \
    python3-opencv \
    python3-pip \
    python3-setuptools \
    python3-wheel

RUN python3 -m pip install --upgrade pip && \
    pip install cmake_format
